version: '3.7'

services:
  trino:
    hostname: trino
    image: 'trinodb/trino:latest'
    ports:
      - '8080:8080'
    volumes:
      - ./trino-etc:/etc/trino
    networks:
      - appnet
    
  minio:
    hostname: minio
    image: 'quay.io/minio/minio:latest'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data --console-address ":9001"
    networks:
      - appnet

  hive-metastore:
    hostname: spark
    build: .
    ports:
      - '9083:9083' 
    depends_on:
      - postgres
    networks:
      - appnet

  postgres:
    container_name: postgres
    image: postgres:14.6
    env_file:
      - .env
    networks:
      - appnet
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./docker-scripts/postgres/init-identity-db.sh:/docker-entrypoint-initdb.d/1-init.sh
      - ./docker-scripts/postgres/init-keycloak-db.sh:/docker-entrypoint-initdb.d/2-init.sh
      - ./docker-scripts/postgres/init-business-db.sh:/docker-entrypoint-initdb.d/3-init.sh
      - pgdata:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    networks:
      - appnet
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - postgres

  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:20
    ports:
      - ${KEYCLOAK_PORT}:8080
    networks:
      - appnet
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=${KEYCLOAK_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_DATABASE_HOST=${KEYCLOAK_DB_HOST}
      - KEYCLOAK_DATABASE_PORT=${POSTGRES_PORT}
      - KEYCLOAK_DATABASE_NAME=${KEYCLOAK_DB_NAME}
      - KEYCLOAK_DATABASE_USER=${KEYCLOAK_DB_USER}
      - KEYCLOAK_DATABASE_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    depends_on:
      - postgres

 
networks:
  appnet:

volumes:
  minio-data:
    driver: local
  pgdata: